import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header/header.js";
import Footer from "../components/footer/footer";
import { AuthContextProvide } from "../components/authContext.js";
import React from "react";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flash Focus",
  description: "Generated by create next app",
};

// MainContent.js

const MainContent = ({ children }) => {
  return (
    <main className="main-content">
      <div className="background-animation"></div>
      <div className="stars"></div>

      {children}
    </main>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <ClerkProvider>
          <AuthContextProvide>
            <div className="page-wrapper">
              <Header />
              <MainContent>{children}</MainContent>
              <Footer />
            </div>
          </AuthContextProvide>
        </ClerkProvider>
      </body>
    </html>
  );
}
